version: '3.7'

services: 
  # Backend API
  smart-brain-api: 
    container_name: backend
    build: ./
    command: yarn start -L
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://shicks:dockerpass@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    ports:
      - "5000:5000"
    volumes: 
      - ./:/usr/src/smart-brain-api
  
  # Postgres
  postgres:
    environment:
      POSTGRES_USER: shicks
      POSTGRES_PASSWORD: dockerpass
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports: 
    - '5432:5432'

    # Redis
  redis:
    image: redis
    ports:
    - "6379:6379"